name: cscb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=2.0.2
  - pandas=2.2.3
  - matplotlib=3.9.3
  - scipy=1.14.1
  - scikit-learn=1.6.0
  - pip
  - pip:
    - scanpy==1.10.3
    - anndata==0.11.1
