name: cscb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=2.0.2
  - pandas=2.2.3
  - matplotlib=3.9.3
  - scipy=1.14.1
  - scikit-learn=1.6.0
  - igraph=0.11.8
  - leidenalg=0.10.2
  - pip
  - pip:
    - scanpy==1.10.3
    - anndata==0.11.1
    - bbknn==1.6.0
    - umap-learn==0.5.7
    - pySingleCellNet==0.1.3
